# Generated by Django 4.0.5 on 2022-07-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
