# Generated by Django 4.0.5 on 2022-07-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_banned_ip_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
