# Generated by Django 4.0.5 on 2022-07-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_member_user_alter_post_user_alter_reply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_deleted',
        ),
    ]
